INSERT INTO categories (id, name, slug) VALUES
  ('cat-vegetables', 'Rau xanh', 'rau-xanh'),
  ('cat-fruits', 'Trái cây', 'trai-cay'),
  ('cat-drinks', 'Đồ uống', 'do-uong'),
  ('cat-dairy-eggs', 'Sữa & trứng', 'sua-trung'),
  ('cat-grains', 'Ngũ cốc', 'ngu-coc'),
  ('cat-snacks', 'Đồ ăn nhẹ', 'do-an-nhe'),
  ('cat-organic', 'Thực phẩm hữu cơ', 'thuc-pham-huu-co'),
  ('cat-fast-food', 'Đồ ăn nhanh', 'do-an-nhanh'),
  ('cat-bakery', 'Bánh', 'banh')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  slug = EXCLUDED.slug,
  updated_at = NOW();

INSERT INTO products (
  id,
  name,
  slug,
  brand,
  category_id,
  description,
  price,
  old_price,
  stock_quantity,
  unit,
  badge,
  accent,
  status
) VALUES
  (
    'prod-oat-honey',
    'Hạt yến mạch mật ong',
    'hat-yen-mach-mat-ong',
    'Green Farm',
    'cat-grains',
    'Yến mạch cán dẹt trộn mật ong rừng, phù hợp cho bữa sáng nhanh và lành mạnh.',
    84000,
    99000,
    42,
    'hộp 500g',
    'Hot',
    '#f5b944',
    'active'
  ),
  (
    'prod-potato-bbq',
    'Snack khoai tây vị BBQ',
    'snack-khoai-tay-vi-bbq',
    'Daily Snack',
    'cat-snacks',
    'Snack khoai tây lát mỏng vị BBQ, giòn nhẹ, dùng cho bữa phụ hoặc tiệc nhỏ.',
    32000,
    39000,
    80,
    'gói 120g',
    'Sale',
    '#e85d3f',
    'active'
  ),
  (
    'prod-veggie-juice',
    'Nước ép rau củ mix',
    'nuoc-ep-rau-cu-mix',
    'Freshy',
    'cat-drinks',
    'Nước ép phối rau củ, vị nhẹ, không thêm đường tinh luyện.',
    46000,
    NULL,
    36,
    'chai 300ml',
    'Mới',
    '#3bb77e',
    'active'
  ),
  (
    'prod-roasted-coffee',
    'Cà phê hạt rang mộc',
    'ca-phe-hat-rang-moc',
    'Bean House',
    'cat-drinks',
    'Cà phê hạt rang mộc, hương chocolate nhẹ, phù hợp pha máy hoặc phin.',
    125000,
    142000,
    24,
    'túi 250g',
    '12%',
    '#9b6b43',
    'active'
  ),
  (
    'prod-peanut-butter',
    'Bơ đậu phộng nguyên chất',
    'bo-dau-phong-nguyen-chat',
    'Nutri Food',
    'cat-organic',
    'Bơ đậu phộng xay mịn, không chất bảo quản, dùng với bánh mì hoặc smoothie.',
    68000,
    NULL,
    33,
    'hũ 220g',
    'Top',
    '#d8902f',
    'active'
  ),
  (
    'prod-veggie-noodle',
    'Mì rau củ ít dầu',
    'mi-rau-cu-it-dau',
    'Healthy Bowl',
    'cat-fast-food',
    'Mì rau củ sấy, ít dầu hơn mì chiên truyền thống, tiện cho bữa nhanh.',
    27000,
    35000,
    96,
    'gói 90g',
    'Giảm',
    '#71b66b',
    'active'
  ),
  (
    'prod-oat-muffin',
    'Bánh muffin yến mạch',
    'banh-muffin-yen-mach',
    'Bakery Lab',
    'cat-bakery',
    'Muffin yến mạch mềm, vị ngọt vừa, dùng cho bữa sáng hoặc trà chiều.',
    55000,
    NULL,
    28,
    'hộp 4 cái',
    'Mới',
    '#c47f53',
    'active'
  ),
  (
    'prod-brown-rice',
    'Gạo lứt hữu cơ',
    'gao-lut-huu-co',
    'Rice Field',
    'cat-grains',
    'Gạo lứt hữu cơ canh tác theo mùa, hạt chắc, dùng cho bữa ăn healthy.',
    96000,
    118000,
    58,
    'túi 1kg',
    '18%',
    '#b89650',
    'active'
  )
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  slug = EXCLUDED.slug,
  brand = EXCLUDED.brand,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock_quantity = EXCLUDED.stock_quantity,
  unit = EXCLUDED.unit,
  badge = EXCLUDED.badge,
  accent = EXCLUDED.accent,
  status = EXCLUDED.status,
  updated_at = NOW();
