apiVersion: v1
kind: Secret
metadata:
  name: greennest-dev-secrets
type: Opaque
stringData:
  JWT_SECRET: devsecops-shop-local-secret
  INTERNAL_SERVICE_TOKEN: devsecops-shop-internal-token
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
  VNPAY_TMN_CODE: ""
  VNPAY_HASH_SECRET: ""
