apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: greennest

resources:
  - prometheus.yaml
  - alertmanager.yaml
  - blackbox-exporter.yaml
  - grafana.yaml
  - jaeger.yaml
  - ingress.yaml
